### ISSUE TITLE
Bafang

### ISSUE THREAD

**Issue by jonra** [jenkie/Arduino-Pedelec-Controller#33]
Hi, would it be possible to get in contact as I'm interested in your project?

**Comment by thomasjfox** [comment]
Sure, you just established first contact :D

Normally all information and request flow through this (sub) forum:
https://www.pedelecforum.de/forum/index.php?forums/forumscontroller.37/

If it's a short question, you can post it here, otherwise I would recommend the forum. May be we'll open an English speaking corner one day, but I'm not sure how happy the forum owners would be.

Be sure to check out the wiki:
https://www.pedelecforum.de/wiki/doku.php?id=elektrotechnik:forumscontroller
And the wiring guide:
https://www.pedelecforum.de/wiki/doku.php?id=elektrotechnik:forumscontroller:peripherie

HTH,
Thomas

**Comment by jonra** [comment]
Thank you for your reply!

Quick version: is this solution compatible with bafang motors? If so, I'll
elaborate in the group :-)

**Comment by thomasjfox** [comment]
This project is a pre-controller for the (Bafang) motor controller. So yes, we are compatible in the way that we output the throttle signal to the real controller.

We have specific support for the BBS02 PAS sensor and you can configure the "gear change time" for these motors. At least that's what I quickly gather from "config.h".

**Comment by thomasjfox** [comment]
Best open an own topic in English like "Question about BBS02 motor" or so :) Give as much detail as possible.

See you over there.
